[package]
name = "plugin-energy-estimation-tdp"
version = "0.1.0"
edition = "2021"

[dependencies]
alumet = { path = "../alumet" }
anyhow = "1.0.89"
humantime-serde = "1.1.1"
serde = { version = "1.0.210", features = ["derive"] }
log = "0.4.22"

[lints]
workspace = true
