[package]
name = "plugin-cgroup"
version = "0.1.0"
edition = "2021"

[dependencies]
alumet = { path = "../alumet" }
log = "0.4.27"
thiserror = "2.0.12"
util-cgroups = { path = "../util-cgroups" }

[dev-dependencies]
tempfile = "3.20.0"
pretty_assertions = "1.4.1"

[lints]
workspace = true
