[package]
name = "plugin-cgroup"
version = "0.1.0"
edition = "2021"

[dependencies]
alumet = { path = "../alumet" }
anyhow = "1.0.98"
log = "0.4.27"
mio = { version = "1.0.4", features = ["os-poll", "os-ext"] }
notify = "8.0.0"
pretty_assertions = "1.4.1"
rustc-hash = "2.1.1"
thiserror = "2.0.12"
walkdir = "2.5.0"

[lints]
workspace = true

[dev-dependencies]
tempfile = "3.20.0"
