[package]
name = "util-cgroups"
version = "0.1.0"
edition = "2021"
description = "Utilities to use control groups, v1 and v2."

[features]
manually = []

[dependencies]
anyhow = "1.0.98"
log = "0.4.27"
mio = { version = "1.0.4", features = ["os-poll", "os-ext"] }
mount-watcher = "0.4.0"
nix = { version = "0.30.1", features = ["inotify"] }
rustc-hash = "2.1.1"
serde = { version = "1.0.219", features = ["derive"]}
thiserror = "2.0.12"
walkdir = "2.5.0"

[dev-dependencies]
criterion = "0.6.0"
pretty_assertions = "1.4.1"
tempfile = "3.20.0"
util-cgroups = { path = ".", features = ["manually"] }

[lints]
workspace = true

[[bench]]
name = "parse"
harness = false # comment this line to run unit tests in benches
