[package]
name = "containers"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
alumet = { path = "../../../core/alumet" }
util-cgroups = { path = "../util-cgroups" }
util-cgroups-plugins = { path = "../util-cgroups-plugins" }

anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }
rustc-hash = "2.0"
humantime-serde = "1.1"
hostname = "0.4"
log = "0.4"

[dev-dependencies]
pretty_assertions = "1.4"
mockito = "1.2"
tempfile = "3.8"