[package]
name = "plugin-socket-control"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alumet = { path = "../alumet" }
anyhow = "1.0.88"
humantime = "2.1.0"
log = "0.4.22"
tokio = { version = "1.40.0", features = ["net", "io-util"] }
tokio-util = "0.7.12"
serde = { version = "1.0.210", features = ["derive"] }

[dev-dependencies]
pretty_assertions = "1.4.0"
regex = "1.11.1"

[lints]
workspace = true
