name: Robot framework files validation

on:
  pull_request:
    paths:
      - integration-tests/**

jobs:
  Robot-validation:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: integration-tests
    steps:
      - uses: actions/checkout@v7

      - name: Install poetry
        run: |
          VERSION_STRING=$(grep "requires-poetry" pyproject.toml | awk '{ print $3 }' | sed -e 's/"//g')
          pipx install poetry"$VERSION_STRING"

      - name: Install python
        uses: actions/setup-python@v6
        with:
          python-version-file: integration-tests/pyproject.toml
          cache: poetry

      - name: Install dependencies
        run: |
          make init

      - name: Robocop check
        run: |
          make lint

      - name: Robocop format
        run: |
          make format-check

      - name: Run Robot Framework Find Unused
        run: |
          make unused
